### ISSUE TITLE
Python version: Linux problem #1: case sensitivity 

### ISSUE THREAD

**Issue by gavpol** [CTinRT/HLUT-guide#1]
Hello! Thank you for providing such extensive code to accompany your interesting consensus paper. I am a Linux user. I set up a conda environment using the yaml file you usefully provided. However, I still had some problems getting your software to run. I managed it, but had to modify the code in places.

Problem #1: case sensitivity

Paths and file names are case sensitive in Linux/UNIX. At various places you have hardcoded paths/filenames and you aren't always consistent in case. Notably;
- _results_ or _Results_ for the ouput data
- the names of the files in _results/for_report/svg_

I guess it runs fine out-of-the-box on Windows/Mac, but I thought it was worth raising the issue.

**Comment by Nils-MP** [comment]
Thank you very much for pointing this out! I adjusted the filenames to be fully consistent between the different files.
