### ISSUE TITLE
Python version: Linux problem #2: ttfonts

### ISSUE THREAD

**Issue by gavpol** [CTinRT/HLUT-guide#2]
Hello! Thank you for providing such extensive code to accompany your interesting consensus paper. I am a Linux user. I set up a conda environment using the yaml file you usefully provided. However, I still had some problems getting your software to run. I managed it, but had to modify the code in places.

Problem #2: ttfonts
When I installed in conda using the yaml file, _reportlab_ didn't seem to include all the necessary fonts in Linux. Times seems to be missing. On lines 70/71 in report.py I replaced:
- times.ttf --> Vera.ttf
- timebd.ttf --> VeraBd.ttf

This worked as a temporary fix.

I guess it runs fine out-of-the-box on Windows/Mac, but I thought it was worth raising the issue.

**Comment by Nils-MP** [comment]
Thank you for pointing this out. We indeed only tested it on Windows and Mac. We changed the fonts so it should now work on Linux out of the box.
